#!/usr/bin/python3
import argparse
from rivuletpy.rtracenet import trace_net

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Arguments to perform the Rivulet2 tracing algorithm.')
    parser.add_argument(
        '-f',
        '--file',
        type=str,
        default=None,
        required=True,
        help='The input file. A image file (*.tif, *.nii, *.mat).')
    parser.add_argument(
        '-o',
        '--out',
        type=str,
        default=None,
        required=False,
        help='The name of the output directory')
    parser.add_argument(
        '-t',
        '--threshold',
        type=float,
        default=None,
        help='threshold to distinguish the foreground and background. Default 0. If threshold<0,' 
             ' Max Entropy will be used.'
    )

    parser.add_argument('--speed', dest='speed', action='store_true',
                        help="Use the input directly as speed image")
    parser.set_defaults(speed=False)

    # Args for tracing
    parser.add_argument('--strictseg', dest='strictseg', action='store_true',
                        help="Segment the neurons strictly around their edges (default)")
    parser.add_argument('--no-strictseg', dest='strictseg', action='store_false',
                        help="Segment the neurons into broader areas (slow)")
    parser.set_defaults(strictseg=True)

    parser.add_argument('--quality', dest='quality', action='store_true',
                        help="Reconstruct the neuron with higher quality and slightly more computing time")
    parser.add_argument('--no-quality', dest='quality', action='store_false',
                        help="Reconstruct the neuron with lower quality and slightly more computing time")
    parser.set_defaults(quality=False)

    parser.add_argument('--forcerecal', dest='forcerecal', action='store_true',
                        help="Force re-application of the algorithm, regardless of the presence of cached files")
    parser.add_argument('--no-forcerecal', dest='forcerecal', action='store_false',
                        help="Use cached files (default)")
    parser.set_defaults(forcerecal=False)

    parser.add_argument('--asynchronous', dest='asynchronous', action='store_true',
                        help="Trace in parallel (default)")
    parser.add_argument('--no-asynchronous', dest='asynchronous', action='store_false',
                        help="Trace cells synchronously (slower, more well-behaved tracebacks)")
    parser.set_defaults(asynchronous=False)

    args = parser.parse_args()

    trace_net(file=args.file, dir_out=args.out, threshold=args.threshold,
              strict_seg=args.strictseg, force_recalculate=args.forcerecal,
              speed=args.speed, quality=args.quality, asynchronous=args.asynch)
